### ISSUE TITLE
async_work_group_copy with destination of mixed type not supported

### ISSUE THREAD

**Issue by robinchrist** [mc-imperial/gpuverify#26]
Hello,

I tried to check a kernel which heavily depends on async_work_group_copy.

`3 warnings generated.
OpenCL3.opt.bc: error: async_work_group_copy with destination of mixed type not supported
Please contact the developers; this is an implementation limitation`

I don't know what this error means, since the destinations are always __local float4*.

**Comment by afd** [comment]
Hi Robin

Would you be able to send a small code example that issues this warning 
where you believe it should not?

Thanks

Ally

**Comment by robinchrist** [comment]
Hi Ally,

I will need to reduce the source code, but I could provide the whole source code via personal message or email.
Would that be okay for you?

**Comment by jeroenk** [comment]
> I don't know what this error means

It's an internal problem in Bugle, GPUVerify's LLVM to Boogie translator. It most likely signals that Bugle's pointer analysis fails to do the right thing on its first iteration. It would be really helpful to see a reduced kernel that triggers this behaviour.

**Comment by robinchrist** [comment]
>  It would be really helpful to see a reduced kernel that triggers this behaviour.
I will provide a reduced kernel as soon as possible.

The kernel uses a double buffering technique with two buffers, where data is asynchronously loaded into the buffer which is not used. After the calculation and the async copy finished, the pointers to the buffers  are swapped.
I assume Boogie is not able to "understand", that the buffers or rather the pointers to them are swapped.

**Comment by jeroenk** [comment]
Going by your description, I guess there’s a loop in which this all happens. If so, cutting down the kernel might be as simple as keeping the loop with the async call(s) and maybe one access to the array you’re actually using.

**Comment by jeroenk** [comment]
I believe I locally have a fix for this issue.

@robinchrist How did you obtain GPUVerify? Did you compile it yourself, or are you using a nightly build? I'm trying to figure out how to best get the fix to you to try.

**Comment by jeroenk** [comment]
@robinchrist Do you use the Windows or the Linux build?

**Comment by robinchrist** [comment]
@jeroenk I am using Windows 10.

**Comment by jeroenk** [comment]
@robinchrist Thanks. In that case I'll create a new Windows nightly for you. Please give me a few days.

**Comment by jeroenk** [comment]
@robinchrist I dropped a new build here: https://github.com/jeroenk/gpuverify/releases/tag/fusion-async (grab the deploy.zip file from there).

Please let me know if this solves your problem.

**Comment by jeroenk** [comment]
@robinchrist Did the updated build work for you?

**Comment by jeroenk** [comment]
We believe we fixed this. Please open a new issue if there are still problems with this.
