### ISSUE TITLE
Crash after filling up all memory (32GB) by solver

### ISSUE THREAD

**Issue by webmaster128** [mc-imperial/gpuverify#37]
I am trying to verify [this OpenCL 1.2 kernel](https://github.com/mc-imperial/gpuverify/files/2851866/kernel.cl.zip) (from https://github.com/webmaster128/nano-vanity/tree/INLINE). I observe multiple compile steps and then a long running z3/cvc4 process. Both solver processes consume very much memory and eventually crash at the point when the system's memory (32GB) is filled up.

Steps to reproduce:

```
apt update && apt upgrade -y && apt autoremove -y && apt install -y python python-psutil unzip mono-complete libgomp1 && reboot

cd ~
git clone --branch INLINE https://github.com/webmaster128/nano-vanity.git
cd nano-vanity/
./merge-kernel.py > kernel.cl

cd ~
wget https://github.com/mc-imperial/gpuverify/releases/download/2018-03-22/GPUVerifyLinux64.zip
unzip GPUVerifyLinux64.zip
cd 2018-03-22
time ./gpuverify --local_size 256 --global_size 1024 --timeout=0 --verbose --cruncher-opt=/proverOpt:VERBOSITY=100 --solver=cvc4 /root/nano-vanity/kernel.cl
```

The output around the crash is

```
[SMT-INP-0] (assert (= $arrayId$$ge25519_niels_base_multiples ...
[SMT-INP-0] (assert (= $arrayId$$null$ #x00))
[SMT-INP-0] (assert (not (= (ite (= group_size_y #x00000001) #...
[SMT-INP-0] (assert (not (= (ite (= group_size_z #x00000001) #...
[SMT-INP-0] (assert (not (= (ite (= num_groups_y #x00000001) #...
[SMT-INP-0] (assert (not (= (ite (= num_groups_z #x00000001) #...
[SMT-INP-0] (assert (not (= (ite (= work_dim #x00000001) #b1 #...
[SMT-INP-0] (assert (not (= (ite (= group_size_x #x00000100) #...
[SMT-INP-0] (assert (not (= (ite (= num_groups_x #x00000004) #...
[SMT-INP-0] (assert (not (= (ite (= global_offset_x #x00000000...
[SMT-INP-0] (assert (not (= (ite (= global_offset_y #x00000000...
[SMT-INP-0] (assert (not (= (ite (= global_offset_z #x00000000...
[SMT-INP-0] (define-fun $generate_pubkey () Bool  (=> (= (Cont...
[SMT-INP-0] (push 1)
[SMT-INP-0] (set-info :boogie-vc-id $generate_pubkey)
[SMT-INP-0] (assert (not  (=> (and (and (and (and (and (and (...
[SMT-INP-0] (get-info :name)
[SMT-OUT-0] (:name "cvc4")
[SMT-INP-0] (check-sat)
[SMT-INP-0] (get-info :name)
[SMT-INP-0] (pop 1)

GPUVerify: an internal error has occurred, details written to __gvdump.txt.
```

The behaviour without the `--solver=cvc4` argument was very similar.

Any ideas what could cause such a high memory consumption? Thanks a lot in advance!

**Comment by jeroenk** [comment]
> Any ideas what could cause such a high memory consumption? Thanks a lot in advance!

Yes, it's probably a combination of two things:

1. the kernel is pretty massive
1. at first glance it seems to use some loop idioms for which I don't think we automatically infer loop invariants; this means that the solver will try to come up with a counterexample that shows that there's a data race somewhere (likely a false positive), which in my experience can consume quite a lot of memory.

Some tips on how to proceed with this:
* It looks to me that the kernel works in several modes based on `generate_key_type`. To start I would focus on a single mode and comment out all code in ` generate_pubkey` the not run in that particular mode. Once things work for one mode, you can move on to the next, and once each verifies on its own, you could attempt a full verification again.
* Follow the control flow in the kernel (including that in functions that are being called) until you reach the first loop. Comment out all code that would be executed after that loop. If that gives you something that verifies, re-enable everything up to and including the next loop. Repeat until GPUVerify reports a data race error or until all code is re-enabled.

If GPUVerify reports a data race then, it might be required to manually specify loop invariants. Let's continue the discussion here when you reach that point. Of course, it might also run out of memory again. In that case we might try verifying the kernel for each shared array separately (in combination with the above steps), but let's not go into this for now.

**Comment by jeroenk** [comment]
Forgot to add: you probably want to stick with CVC4. In our experience it often performs better than Z3 for the kinds of problems GPUVerify gives it.

**Comment by webmaster128** [comment]
Thanks a lot! This gives a clear path forward. It will probably take some time to gather all the findings but I'll get back as soon as I know more.

One more question: do you know if `--local_size` and `--global_size` have a significant impact on solver performance? My programm does not rely on syncing threads and the work packages are independent of each other, so I could as well test with local size 2 and global size 4 to get started.

**Comment by jeroenk** [comment]
Stick to powers-of-two, I would suggest.

**Comment by jeroenk** [comment]
Closing, as this issue has been inactive for a while, and as it is not technically a bug in the tooling. Feel free to re-open if more discussion is required.

**Comment by webmaster128** [comment]
Yes, you are right. Will not follow up on this for the time being. Thank you the the incredible tooling, the maintenance and support!
