### ISSUE TITLE
Add TravisCI and DockerBuild integration

### ISSUE THREAD

**Issue by delcypher** [mc-imperial/gpuverify#4]
Once this repo becomes public we should add TravisCI and DockerBuild integration so that tests run automatically for every push and so tests get run on pull requests. The Docker integration would also mean the a new Docker image would be built for every push (provided the tests pass).

**Comment by jeroenk** [comment]
Closing this, as we have a basic TravisCI setup now, although it still needs to be enhanced.

I dropped the Docker image, as I neither have the ability nor the motivation to maintain it.
