### ISSUE TITLE
fdim is not implemented

### ISSUE THREAD

**Issue by VincentSC** [mc-imperial/gpuverify#6]
When [fdim](https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/fdim.html) is used in a kernel, it complaints about a redefenition.

**Comment by jeroenk** [comment]
@VincentSC It complains about a missing definition in my case, is that what you mean?
```
kernel.cl:5:25: error: implicit declaration of function 'fdim' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  A[get_global_id(0)] = fdim(A[get_global_id(0)], B[get_global_id(0)]);
                        ^
1 error generated.
```
If not, then I would more details on how to reproduce the problem.

**Comment by VincentSC** [comment]
Yes, that's what I meant.

**Comment by jeroenk** [comment]
I've added the float versions of `fdim`. To get it you need to update the bugle component of GPUVerify, or more precisely, you'll need to get the latest version of the `opencl_builtins.h` that comes with it: https://github.com/mc-imperial/bugle/blob/master/include-blang/opencl_builtins.h

The underlying OpenCL runtime library that we're using is incomplete. I'm generally adding builtins when there is a demand for them; there are so many that I cannot added all at once. I'll happily add more if you need them, please let us know.
