### ISSUE TITLE
Method getIncludes on class GPUVerifyInstance maybe have bug.

### ISSUE THREAD

**Issue by CrazyUmka** [mc-imperial/gpuverify#7]
Check this please: https://github.com/mc-imperial/gpuverify/blob/master/GPUVerify.py#L280
When trying to add an includes directory for search with argument -I, the includes field of the GPUVerifyInstance class did not get the specified directories. But maybe I wrong.

**Comment by jeroenk** [comment]
Fixed, thanks for the report.
